### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Frutik349** [BlueTree242/AdvancedPlHide#11]
When I find out the cheat plugins spam 'false false'
![изображение](https://github.com/BlueTree242/AdvancedPlHide/assets/138368005/ac69b00c-8577-4ef8-9bd0-7d73b7736eda)
+ when you write in the chat '/luckperms' it writes the name of the plugin and in theory it should be blocked, but it doesn’t

**Comment by BlueTree242** [comment]
This issue has been fixed (on `develop` branch) a very long tme ago.
