### ISSUE TITLE
Will plugin on spigot block bungee commands too?

### ISSUE THREAD

**Issue by TymekSL** [BlueTree242/AdvancedPlHide#12]
I want whitelist mode (showing only user commands after / ) , plugin will be on survival (example) when I add bungee command example /faq, will this work? In the plhidepro I must have plugin on bungee too , it's useleess because I want remove protocolize due to other good pluin which does not support this - nevermind. Hope to fast answer

**Comment by A248** [comment]
It's not possible for a spigot plugin to block bungee commands.

**Comment by BlueTree242** [comment]
> I want whitelist mode (showing only user commands after / ) , plugin will be on survival (example) when I add bungee command example /faq, will this work? In the plhidepro I must have pluginon bungee too , its useleess because I want remove protocolize due to other good pluin which not support this - nevermind. HOpe to fast answer

I'm assuming you are talking about GeyserMC being incompatible with protocolize? Is that why?

**Comment by TymekSL** [comment]
> > I want whitelist mode (showing only user commands after / ) , plugin will be on survival (example) when I add bungee command example /faq, will this work? In the plhidepro I must have pluginon bungee too , its useleess because I want remove protocolize due to other good pluin which not support this - nevermind. HOpe to fast answer
> 
> I'm assuming you are talking about GeyserMC being incompatible with protocolize? Is that why?

No, i just want using plugin which not support protocolize no geysermc

**Comment by TymekSL** [comment]
> > I want whitelist mode (showing only user commands after / ) , plugin will be on survival (example) when I add bungee command example /faq, will this work? In the plhidepro I must have pluginon bungee too , its useleess because I want remove protocolize due to other good pluin which not support this - nevermind. HOpe to fast answer
> 
> I'm assuming you are talking about GeyserMC being incompatible with protocolize? Is that why?

Taking abiut Fallback server

**Comment by TymekSL** [comment]
> It's not possible for a spigot plugin to block bungee commands.

Bruh learn read, i want add bungee cmd to tab complete on spigot not blocking it. And waiting for developer answer not your

**Comment by Creeperz653** [comment]
Learn to respect watch your tone.

> > It's not possible for a spigot plugin to block bungee commands.
> 
> Bruh learn read, i want add bungee cmd to tab complete on spigot not blocking it. And waiting for developer answer not your

**Comment by BlueTree242** [comment]
> > It's not possible for a spigot plugin to block bungee commands.
> 
> Bruh learn read, i want add bungee cmd to tab complete on spigot not blocking it. And waiting for developer answer not your

As creeperz said, please watch your language. People are trying to help you. Your messages are full of spelling and grammar mistakes, and they are unclear. Please mention what is currently the output, what you want the output to be, and what you tried to do (even if you tried another plugin).

**Comment by TymekSL** [comment]
> > > It's not possible for a spigot plugin to block bungee commands.
> > 
> > 
> > Bruh learn read, i want add bungee cmd to tab complete on spigot not blocking it. And waiting for developer answer not your
> 
> As creeperz said, please watch your language. People are trying to help you. Your messages are full of spelling and grammar mistakes, and they are unclear. Please mention what is currently the output, what you want the output to be, and what you tried to do (even if you tried another plugin).

14:23:56 INFO]: [AdvancedPlHide] Enabling AdvancedPlHide v2.4*
[14:23:57 ERROR]: Error occurred while enabling AdvancedPlHide v2.4 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolManager
        at tk.bluetree242.advancedplhide.spigot.AdvancedPlHideSpigot.onEnable(AdvancedPlHideSpigot.java:82) ~[AdvancedPlHide-2.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-461]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-461]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-461]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-461]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolManager
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 13 more
[14:23:57 INFO]: [AdvancedPlHide] Disabling AdvancedPlHide v2.4
[14:23:57 ERROR]: Error occurred while disabling AdvancedPlHide v2.4
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolManager
        at tk.bluetree242.advancedplhide.spigot.AdvancedPlHideSpigot.onDisable(AdvancedPlHideSpigot.java:105) ~[AdvancedPlHide-2.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[paper-1.20.4.jar:git-Paper-461]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-461]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.20.4.jar:git-Paper-461]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-461]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-461]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-461]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolManager
        ... 16 more

**Comment by TymekSL** [comment]
now plugin totally not working dx 
p.s i want answer from main developer, not other users

**Comment by TymekSL** [comment]
> Bruh learn read, i want add bungee cmd to tab complete on spigot not blocking i

want add bungee cmd to tab complete on spigot not blocking

**Comment by BlueTree242** [comment]
> now plugin totally not working dx p.s i want answer from main

> > > > It's not possible for a spigot plugin to block bungee commands.
> > > 
> > > 
> > > Bruh learn read, i want add bungee cmd to tab complete on spigot not blocking it. And waiting for developer answer not your
> > 
> > 
> > As creeperz said, please watch your language. People are trying to help you. Your messages are full of spelling and grammar mistakes, and they are unclear. Please mention what is currently the output, what you want the output to be, and what you tried to do (even if you tried another plugin).
> 
> 14:23:56 INFO]: [AdvancedPlHide] Enabling AdvancedPlHide v2.4* [14:23:57 ERROR]: Error occurred while enabling AdvancedPlHide v2.4 (Is it up to date?) java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolManager at tk.bluetree242.advancedplhide.spigot.AdvancedPlHideSpigot.onEnable(AdvancedPlHideSpigot.java:82) ~[AdvancedPlHide-2.4.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-461] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-461] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-461] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-461] at java.lang.Thread.run(Thread.java:840) ~[?:?] Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolManager at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] ... 13 more [14:23:57 INFO]: [AdvancedPlHide] Disabling AdvancedPlHide v2.4 [14:23:57 ERROR]: Error occurred while disabling AdvancedPlHide v2.4 java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolManager at tk.bluetree242.advancedplhide.spigot.AdvancedPlHideSpigot.onDisable(AdvancedPlHideSpigot.java:105) ~[AdvancedPlHide-2.4.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[paper-1.20.4.jar:git-Paper-461] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-461] at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.20.4.jar:git-Paper-461] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-461] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-461] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-461] at java.lang.Thread.run(Thread.java:840) ~[?:?] Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolManager ... 16 more

Please make sure you have ProtocolLib 5.1.0+ (dev build) installed

**Comment by BlueTree242** [comment]
> > Bruh learn read, i want add bungee cmd to tab complete on spigot not blocking i
> 
> want add bungee cmd to tab complete on spigot not blocking

Please clarify, or show example or talk in your native language and we'll translate

**Comment by TymekSL** [comment]
> > > Bruh learn read, i want add bungee cmd to tab complete on spigot not blocking i
> > 
> > 
> > want add bungee cmd to tab complete on spigot not blocking
> 
> Please clarify, or show example or talk in your native language and we'll translate

Chce dodać komendę /faq do listy tab complete dla gracza. Plugin FAQ jest na bungee, chce wiedzieć czy zadziała używając wersji spigot

**Comment by BlueTree242** [comment]
> > > > Bruh learn read, i want add bungee cmd to tab complete on spigot not blocking i
> > > 
> > > 
> > > want add bungee cmd to tab complete on spigot not blocking
> > 
> > 
> > Please clarify, or show example or talk in your native language and we'll translate
> 
> Chce dodać komendę /faq do listy tab complete dla gracza. Plugin FAQ jest na bungee, chce wiedzieć czy zadziała używając wersji spigot

The plugin can only remove/block commands in tab completion it cannot add new ones

**Comment by TymekSL** [comment]
> > > > > Bruh learn read, i want add bungee cmd to tab complete on spigot not blocking i
> > > > 
> > > > 
> > > > want add bungee cmd to tab complete on spigot not blocking
> > > 
> > > 
> > > Please clarify, or show example or talk in your native language and we'll translate
> > 
> > 
> > Chce dodać komendę /faq do listy tab complete dla gracza. Plugin FAQ jest na bungee, chce wiedzieć czy zadziała używając wersji spigot
> 
> The plugin can only remove/block commands in tab completion it cannot add new ones

Nie rozumiem co piszesz, wiem (chyba) jak to działa
Chce pod / mieć dozwolone komendy dla gracza, dla moderatora, dla admina itd. i chce również mieć /faq który jest pluginem bungee
Jeśli możesz proszę rozjasnij mi czy to zadziała
Po prostu chce pod tab whitelist mieć /faq

**Comment by TymekSL** [comment]
> > now plugin totally not working dx p.s i want answer from main
> 
> > > > > It's not possible for a spigot plugin to block bungee commands.
> > > > 
> > > > 
> > > > Bruh learn read, i want add bungee cmd to tab complete on spigot not blocking it. And waiting for developer answer not your
> > > 
> > > 
> > > As creeperz said, please watch your language. People are trying to help you. Your messages are full of spelling and grammar mistakes, and they are unclear. Please mention what is currently the output, what you want the output to be, and what you tried to do (even if you tried another plugin).
> > 
> > 
> > 14:23:56 INFO]: [AdvancedPlHide] Enabling AdvancedPlHide v2.4* [14:23:57 ERROR]: Error occurred while enabling AdvancedPlHide v2.4 (Is it up to date?) java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolManager at tk.bluetree242.advancedplhide.spigot.AdvancedPlHideSpigot.onEnable(AdvancedPlHideSpigot.java:82) ~[AdvancedPlHide-2.4.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-461] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-461] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-461] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-461] at java.lang.Thread.run(Thread.java:840) ~[?:?] Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolManager at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] ... 13 more [14:23:57 INFO]: [AdvancedPlHide] Disabling AdvancedPlHide v2.4 [14:23:57 ERROR]: Error occurred while disabling AdvancedPlHide v2.4 java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolManager at tk.bluetree242.advancedplhide.spigot.AdvancedPlHideSpigot.onDisable(AdvancedPlHideSpigot.java:105) ~[AdvancedPlHide-2.4.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[paper-1.20.4.jar:git-Paper-461] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-461] at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.20.4.jar:git-Paper-461] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-461] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-461] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-461] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-461] at java.lang.Thread.run(Thread.java:840) ~[?:?] Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolManager ... 16 more
> 
> Please make sure you have ProtocolLib 5.1.0+ (dev build) installed

Of course! But wait meaby there is newer

**Comment by BlueTree242** [comment]
> Nie rozumiem co piszesz, wiem (chyba) jak to działa
> Chce pod / mieć dozwolone komendy dla gracza, dla moderatora, dla admina itd. i chce również mieć /faq który jest pluginem bungee
> Jeśli możesz proszę rozjasnij mi czy to zadziała
> Po prostu chce pod tab whitelist mieć /faq

If you install the plugin on a spigot server, it will whitelist commands on spigot only, which means all bungee commands will still be visible, because it is impossible for spigot server to prevent bungee from adding commands. 

There's also something i have to make clear, plugin does not prevent the command from running, it only hides it. Preventing the command from running can easily be achieved via hundreds of other plugins.

**Comment by TymekSL** [comment]
> > Nie rozumiem co piszesz, wiem (chyba) jak to działa
> > Chce pod / mieć dozwolone komendy dla gracza, dla moderatora, dla admina itd. i chce również mieć /faq który jest pluginem bungee
> > Jeśli możesz proszę rozjasnij mi czy to zadziała
> > Po prostu chce pod tab whitelist mieć /faq
> 
> If you install the plugin on a spigot server, it will whitelist commands on spigot only, which means all bungee commands will still be visible, because it is impossible for spigot server to prevent bungee from adding commands.
> 
> There's also something i have to make clear, plugin does not prevent the command from running, it only hides it. Preventing the command from running can easily be achieved via hundreds of other plugins.

I just simple add the /faq visible in the tab complete

**Comment by TymekSL** [comment]
Testing this and gave permission as default member for whitelist mode. In whitelist there is 
    tabcomplete:
     - "warp"
     - "kit"
and when joined server and make / there is 0 command, have you got discord? Could we move there?

**Comment by BlueTree242** [comment]
> Testing this and gave permission as default member for whitelist mode. In whitelist there is tabcomplete: - "warp" - "kit" and when joined server and make / there is 0 command, have you got discord? Could we move there?

Yes there is a discord server https://discord.com/invite/MMMQHA4

**Comment by BlueTree242** [comment]
Hey, did you join the discord server?

**Comment by BlueTree242** [comment]
Hello, this issue is closed due to inactivity
